name: Generate HSR Wiki Pages

on:
  workflow_dispatch:

jobs:
  build-and-generate:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Run Generator Utilities
        run: |
          pnpm exec ts-node src/scripts/dump_all_consumables.ts
          pnpm exec ts-node src/scripts/dump_all_items.ts
          pnpm exec ts-node src/scripts/dump_all_readables.ts
          pnpm exec ts-node src/scripts/dump_all_shops.ts
          pnpm exec ts-node src/scripts/dump_extra_effects.ts
          pnpm exec ts-node src/scripts/dump_all_tutorials.ts
          pnpm exec ts-node src/scripts/dump_audience_dice.ts
          pnpm exec ts-node src/scripts/dump_curios.ts
          pnpm exec ts-node src/scripts/dump_equations.ts
          pnpm exec ts-node src/scripts/dump_loading_screens.ts
          pnpm exec ts-node src/scripts/dump_messages.ts
          pnpm exec ts-node src/scripts/dump_relics.ts
          pnpm exec ts-node src/scripts/dump_scepters.ts
          pnpm exec ts-node src/scripts/dump_su_stages.ts
          pnpm exec ts-node src/scripts/dump_und_secrets.ts
          pnpm exec ts-node src/scripts/dump_weekly_du.ts
          pnpm exec ts-node src/scripts/dump_odes.ts
          pnpm exec ts-node src/scripts/dump_boons.ts
          pnpm exec ts-node src/scripts/character_page_links.ts
          pnpm exec ts-node src/scripts/dump_occurrences.ts
          pnpm exec ts-node src/scripts/dump_talksentences.ts
          pnpm exec ts-node src/scripts/vo/dump_vo_names.ts
          pnpm exec ts-node src/scripts/vo/dump_sound_events.ts
          pnpm exec ts-node src/scripts/dump_missions.ts --no-dialogue

      - name: Upload Generated Pages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-wiki-pages
          path: output/
          retention-days: 7
